### PR TITLE
#Milestone 1: Prepare data architecture documentation

### PR DESCRIPTION
**Pull request by julian3493**
- Add entities in the ERD
- Add type for each field in the ERD
- Add relationships required for each entity in the ERD
- Add primary and foreign keys in entities in the ERD
- Add ERD in Docs folder

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @julian3493  ! 👋 👋 

#### You have done well so far :clap: However, there are changes required for you to make in order for this milestone to be approved. Kindly work on them and submit them for another code review.

**Recommended**

- [x] Friendship table has status or confirmed column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/status.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
-  Please include a column in your friendship model to confirm the friendship. Remember a user can invite someone but the other person has to accept to actually be a friendship.
- [x] User table has `image_link` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by julian3493** [comment]
Thank you for your review, I split friendship requests and friendships into 2 tables, Friendship which contains all confirmed friendships, and Invitation which contains the friendship requests, so I don't need to add the status field in the friendship model.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [x] Kindly remove the Invitation table as the friendship table serve the same purpose
- [x] Also add Status or Confirm to Friendship table
- [x] Kindly activate linter checks for this project
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by kitpao — CHANGES_REQUESTED** [review]
# 👋 Hello @julian3493 

Good job on the project, seems like you got the general idea of how it should behave in the backend 🌟 
**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- [x] **OPTIONAL** Sorry if this was not told before, but you don't need to put type boolean to the like, because you could just check if a "like" exists or not (create o destroy likes between users and posts). That is the way how it is implemented in the scaffold ;) You can delete that column from the Like table

- [x] **MANDATORY** Your linters are not showing in this Pull Request yet, please correct them until you get a message similar to this one: (**Hint:** You may need to reopen the pull request, in that case, please refer to this pull request typing #1 and selecting the menu that appears)
image

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Comment by julian3493** [comment]
Thank you for your review, I think to use that boolean to differentiate likes and dislikes.

**Pull request closed without merging**
